BEGIN {
S["am__EXEEXT_FALSE"]=""
S["am__EXEEXT_TRUE"]="#"
S["LTLIBOBJS"]=""
S["LIBOBJS"]=""
S["LIBC_MACHINE_LIB"]="machine/lib.a"
S["ENABLE_NEWLIB_ICONV_FALSE"]=""
S["ENABLE_NEWLIB_ICONV_TRUE"]="#"
S["HAVE_LONG_DOUBLE_FALSE"]="#"
S["HAVE_LONG_DOUBLE_TRUE"]=""
S["LIBC_SYS_LIB"]=""
S["extra_dir"]=""
S["LIBC_EXTRA_DEF"]=""
S["LIBC_EXTRA_LIB"]=""
S["HAVE_UNIX_DIR_FALSE"]=""
S["HAVE_UNIX_DIR_TRUE"]="#"
S["LIBC_UNIX_LIB"]=""
S["HAVE_SYSCALL_DIR_FALSE"]=""
S["HAVE_SYSCALL_DIR_TRUE"]="#"
S["LIBC_SYSCALL_LIB"]=""
S["HAVE_XDR_DIR_FALSE"]=""
S["HAVE_XDR_DIR_TRUE"]="#"
S["LIBC_XDR_DEF"]=""
S["LIBC_XDR_LIB"]=""
S["HAVE_POSIX_DIR_FALSE"]=""
S["HAVE_POSIX_DIR_TRUE"]="#"
S["LIBC_POSIX_DEF"]=""
S["LIBC_POSIX_LIB"]=""
S["HAVE_STDIO64_DIR_FALSE"]=""
S["HAVE_STDIO64_DIR_TRUE"]="#"
S["LIBC_STDIO64_DEF"]=""
S["LIBC_STDIO64_LIB"]=""
S["HAVE_STDIO_DIR_FALSE"]="#"
S["HAVE_STDIO_DIR_TRUE"]=""
S["LIBC_STDIO_DEF"]="stdio/stmp-def"
S["LIBC_STDIO_LIB"]="stdio/lib.a"
S["HAVE_SIGNAL_DIR_FALSE"]="#"
S["HAVE_SIGNAL_DIR_TRUE"]=""
S["LIBC_SIGNAL_DEF"]="signal/stmp-def"
S["LIBC_SIGNAL_LIB"]="signal/lib.a"
S["HAVE_AEABI_DIR_FALSE"]=""
S["HAVE_AEABI_DIR_TRUE"]="#"
S["LIBC_AEABI_LIB"]=""
S["CRT0"]=""
S["subdirs"]=" machine sys"
S["CPP"]=""
S["OTOOL64"]=""
S["OTOOL"]=""
S["LIPO"]="nios2-elf-lipo"
S["NMEDIT"]=""
S["DSYMUTIL"]=""
S["LN_S"]=""
S["NM"]="nios2-elf-nm"
S["ac_ct_DUMPBIN"]=""
S["DUMPBIN"]=""
S["LD"]="nios2-elf-ld"
S["FGREP"]=""
S["EGREP"]=""
S["GREP"]=""
S["EXEEXT"]=""
S["ac_ct_CC"]=""
S["CPPFLAGS"]=""
S["CFLAGS"]="-g -Os -ffunction-sections -fdata-sections -mno-gpopt"
S["LIBTOOL"]=""
S["OBJDUMP"]="nios2-elf-objdump"
S["DLLTOOL"]="nios2-elf-dlltool"
S["SED"]="/bin/sed"
S["NEWLIB_NANO_MALLOC_FALSE"]="#"
S["NEWLIB_NANO_MALLOC_TRUE"]=""
S["sys_dir"]=""
S["machine_dir"]="nios2"
S["libm_machine_dir"]=""
S["lpfx"]="lib_a-"
S["aext"]="a"
S["oext"]="o"
S["OBJEXT"]="o"
S["USE_LIBTOOL_FALSE"]=""
S["USE_LIBTOOL_TRUE"]="#"
S["ELIX_LEVEL_4_FALSE"]=""
S["ELIX_LEVEL_4_TRUE"]="#"
S["ELIX_LEVEL_3_FALSE"]=""
S["ELIX_LEVEL_3_TRUE"]="#"
S["ELIX_LEVEL_2_FALSE"]=""
S["ELIX_LEVEL_2_TRUE"]="#"
S["ELIX_LEVEL_1_FALSE"]=""
S["ELIX_LEVEL_1_TRUE"]="#"
S["ELIX_LEVEL_0_FALSE"]="#"
S["ELIX_LEVEL_0_TRUE"]=""
S["LDFLAGS"]=""
S["NO_INCLUDE_LIST"]=" rpc/types.h rpc/xdr.h"
S["NEWLIB_CFLAGS"]=" -O2 -DHAVE_GETTIMEOFDAY -DWANT_SMALL_STDIO -DHAVE_RENAME -DWANT_PRINTF_LONG_LONG -D_REENT_SMALL -DPREFER_SIZE_OVER_SPEED -DNO_FLOATING_POINT -DSMAL"\
"L_MEMORY  -DMALLOC_LOCK_PROVIDED -DMALLOC_LOCK=__malloc_lock -DMALLOC_UNLOCK=__malloc_unlock -DENV_LOCK_PROVIDED -DENV_LOCK=__env_lock -DENV_UNLOCK="\
"__env_unlock -DHAVE_RENAME -DMISSING_SYSCALL_NAMES -fno-builtin"
S["CCASFLAGS"]="-g -Os -ffunction-sections -fdata-sections -mno-gpopt"
S["CCAS"]="/cygdrive/c/Users/mtaha/Desktop/Uni/Year_3_2021_2022/ECE342_Labs/Lab6/part3/software/sine_approx_bsp/newlib-build-tmp/build-newlib-stage-wrapper nio"\
"s2-elf-gcc -B/cygdrive/c/Users/mtaha/Desktop/Uni/Year_3_2021_2022/ECE342_Labs/Lab6/part3/software/sine_approx_bsp/newlib-build-tmp/smallc/nios2-elf/"\
"newlib/ -isystem /cygdrive/c/Users/mtaha/Desktop/Uni/Year_3_2021_2022/ECE342_Labs/Lab6/part3/software/sine_approx_bsp/newlib-build-tmp/smallc/nios2-"\
"elf/newlib/targ-include -isystem /cygdrive/c/intelfpga_lite/18.0/nios2eds/bin/gnu/src/newlib-2.2/newlib/libc/include -B/cygdrive/c/Users/mtaha/Deskt"\
"op/Uni/Year_3_2021_2022/ECE342_Labs/Lab6/part3/software/sine_approx_bsp/newlib-build-tmp/smallc/nios2-elf/libgloss/nios2 -L/cygdrive/c/Users/mtaha/D"\
"esktop/Uni/Year_3_2021_2022/ECE342_Labs/Lab6/part3/software/sine_approx_bsp/newlib-build-tmp/smallc/nios2-elf/libgloss/libnosys -L/cygdrive/c/intelf"\
"pga_lite/18.0/nios2eds/bin/gnu/src/newlib-2.2/libgloss/nios2   "
S["MAINT"]="#"
S["MAINTAINER_MODE_FALSE"]=""
S["MAINTAINER_MODE_TRUE"]="#"
S["READELF"]="nios2-elf-readelf"
S["RANLIB"]="/cygdrive/c/Users/mtaha/Desktop/Uni/Year_3_2021_2022/ECE342_Labs/Lab6/part3/software/sine_approx_bsp/newlib-build-tmp/build-newlib-stage-wrapper nio"\
"s2-elf-ranlib"
S["AR"]="/cygdrive/c/Users/mtaha/Desktop/Uni/Year_3_2021_2022/ECE342_Labs/Lab6/part3/software/sine_approx_bsp/newlib-build-tmp/build-newlib-stage-wrapper nio"\
"s2-elf-ar"
S["AS"]="/cygdrive/c/Users/mtaha/Desktop/Uni/Year_3_2021_2022/ECE342_Labs/Lab6/part3/software/sine_approx_bsp/newlib-build-tmp/build-newlib-stage-wrapper nio"\
"s2-elf-as"
S["am__fastdepCC_FALSE"]="#"
S["am__fastdepCC_TRUE"]=""
S["CCDEPMODE"]="depmode=gcc3"
S["am__nodep"]="_no"
S["AMDEPBACKSLASH"]="\\"
S["AMDEP_FALSE"]="#"
S["AMDEP_TRUE"]=""
S["am__quote"]=""
S["am__include"]="include"
S["DEPDIR"]=".deps"
S["CC"]="/cygdrive/c/Users/mtaha/Desktop/Uni/Year_3_2021_2022/ECE342_Labs/Lab6/part3/software/sine_approx_bsp/newlib-build-tmp/build-newlib-stage-wrapper nio"\
"s2-elf-gcc -B/cygdrive/c/Users/mtaha/Desktop/Uni/Year_3_2021_2022/ECE342_Labs/Lab6/part3/software/sine_approx_bsp/newlib-build-tmp/smallc/nios2-elf/"\
"newlib/ -isystem /cygdrive/c/Users/mtaha/Desktop/Uni/Year_3_2021_2022/ECE342_Labs/Lab6/part3/software/sine_approx_bsp/newlib-build-tmp/smallc/nios2-"\
"elf/newlib/targ-include -isystem /cygdrive/c/intelfpga_lite/18.0/nios2eds/bin/gnu/src/newlib-2.2/newlib/libc/include -B/cygdrive/c/Users/mtaha/Deskt"\
"op/Uni/Year_3_2021_2022/ECE342_Labs/Lab6/part3/software/sine_approx_bsp/newlib-build-tmp/smallc/nios2-elf/libgloss/nios2 -L/cygdrive/c/Users/mtaha/D"\
"esktop/Uni/Year_3_2021_2022/ECE342_Labs/Lab6/part3/software/sine_approx_bsp/newlib-build-tmp/smallc/nios2-elf/libgloss/libnosys -L/cygdrive/c/intelf"\
"pga_lite/18.0/nios2eds/bin/gnu/src/newlib-2.2/libgloss/nios2   "
S["am__untar"]="$${TAR-tar} xf -"
S["am__tar"]="$${TAR-tar} chof - \"$$tardir\""
S["AMTAR"]="$${TAR-tar}"
S["am__leading_dot"]="."
S["SET_MAKE"]=""
S["AWK"]="gawk"
S["mkdir_p"]="/bin/mkdir -p"
S["MKDIR_P"]="/bin/mkdir -p"
S["INSTALL_STRIP_PROGRAM"]="$(install_sh) -c -s"
S["STRIP"]="nios2-elf-strip"
S["install_sh"]="${SHELL} /cygdrive/c/intelfpga_lite/18.0/nios2eds/bin/gnu/src/newlib-2.2/install-sh"
S["MAKEINFO"]="makeinfo"
S["AUTOHEADER"]="${SHELL} /cygdrive/c/intelfpga_lite/18.0/nios2eds/bin/gnu/src/newlib-2.2/missing --run autoheader"
S["AUTOMAKE"]="${SHELL} /cygdrive/c/intelfpga_lite/18.0/nios2eds/bin/gnu/src/newlib-2.2/missing --run automake-1.11"
S["AUTOCONF"]="${SHELL} /cygdrive/c/intelfpga_lite/18.0/nios2eds/bin/gnu/src/newlib-2.2/missing --run autoconf"
S["ACLOCAL"]="${SHELL} /cygdrive/c/intelfpga_lite/18.0/nios2eds/bin/gnu/src/newlib-2.2/missing --run aclocal-1.11"
S["VERSION"]="2.2.0"
S["PACKAGE"]="newlib"
S["CYGPATH_W"]="cygpath -w"
S["am__isrc"]=" -I$(srcdir)"
S["INSTALL_DATA"]="${INSTALL} -m 644"
S["INSTALL_SCRIPT"]="${INSTALL}"
S["INSTALL_PROGRAM"]="${INSTALL}"
S["host_os"]="elf"
S["host_vendor"]="unknown"
S["host_cpu"]="nios2"
S["host"]="nios2-unknown-elf"
S["build_os"]="cygwin"
S["build_vendor"]="unknown"
S["build_cpu"]="x86_64"
S["build"]="x86_64-unknown-cygwin"
S["newlib_basedir"]="/cygdrive/c/intelfpga_lite/18.0/nios2eds/bin/gnu/src/newlib-2.2/newlib/libc/.."
S["MAY_SUPPLY_SYSCALLS_FALSE"]="#"
S["MAY_SUPPLY_SYSCALLS_TRUE"]=""
S["NEWLIB_NANO_FORMATTED_IO_FALSE"]=""
S["NEWLIB_NANO_FORMATTED_IO_TRUE"]="#"
S["target_alias"]="nios2-elf"
S["host_alias"]="nios2-elf"
S["build_alias"]="x86_64-unknown-cygwin"
S["LIBS"]=""
S["ECHO_T"]=""
S["ECHO_N"]="-n"
S["ECHO_C"]=""
S["DEFS"]="-DPACKAGE_NAME=\\\"newlib\\\" -DPACKAGE_TARNAME=\\\"newlib\\\" -DPACKAGE_VERSION=\\\"2.2.0\\\" -DPACKAGE_STRING=\\\"newlib\\ 2.2.0\\\" -DPACKAGE_BUGREPORT=\\\"\\\" -DPAC"\
"KAGE_URL=\\\"\\\""
S["mandir"]="${datarootdir}/man"
S["localedir"]="${datarootdir}/locale"
S["libdir"]="${exec_prefix}/lib"
S["psdir"]="${docdir}"
S["pdfdir"]="${docdir}"
S["dvidir"]="${docdir}"
S["htmldir"]="${docdir}"
S["infodir"]="${datarootdir}/info"
S["docdir"]="${datarootdir}/doc/${PACKAGE_TARNAME}"
S["oldincludedir"]="/usr/include"
S["includedir"]="${prefix}/include"
S["localstatedir"]="${prefix}/var"
S["sharedstatedir"]="${prefix}/com"
S["sysconfdir"]="${prefix}/etc"
S["datadir"]="${datarootdir}"
S["datarootdir"]="${prefix}/share"
S["libexecdir"]="${exec_prefix}/libexec"
S["sbindir"]="${exec_prefix}/sbin"
S["bindir"]="${exec_prefix}/bin"
S["program_transform_name"]="s&^&nios2-elf-&"
S["prefix"]="/cygdrive/c/Users/mtaha/Desktop/Uni/Year_3_2021_2022/ECE342_Labs/Lab6/part3/software/sine_approx_bsp/newlib"
S["exec_prefix"]="${prefix}"
S["PACKAGE_URL"]=""
S["PACKAGE_BUGREPORT"]=""
S["PACKAGE_STRING"]="newlib 2.2.0"
S["PACKAGE_VERSION"]="2.2.0"
S["PACKAGE_TARNAME"]="newlib"
S["PACKAGE_NAME"]="newlib"
S["PATH_SEPARATOR"]=":"
S["SHELL"]="/bin/sh"
  for (key in S) S_is_set[key] = 1
  FS = ""

}
{
  line = $ 0
  nfields = split(line, field, "@")
  substed = 0
  len = length(field[1])
  for (i = 2; i < nfields; i++) {
    key = field[i]
    keylen = length(key)
    if (S_is_set[key]) {
      value = S[key]
      line = substr(line, 1, len) "" value "" substr(line, len + keylen + 3)
      len += length(value) + length(field[++i])
      substed = 1
    } else
      len += 1 + keylen
  }

  print line
}

